id: P25E94D7D
initial_creation_type: ocr
source_metadata:
  volumes:
    7a05029fbe8f45f69bd8d4014aaaca65:
      base_file: v014.txt
      image_group_id: I1PD95859
      title: དཔལ་ནག་པོ་ཆེན་པོའི་སྒྲུབ་ཐབས།
      total_pages: 1856
      volume_number: 14
